name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    container: kivy/buildozer:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix permissions
        run: |
          git config --global --add safe.directory /__w/oyun-apk/oyun-apk
          chown -R root:root /__w/oyun-apk/oyun-apk

      - name: Install Missing Build-Tools & Aidl
        run: |
          export ANDROID_HOME=/root/.buildozer/android/platform/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
          yes | sdkmanager --licenses || true
          sdkmanager "build-tools;33.0.0" "platforms;android-33" || true

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
