name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache git python3-pip openjdk-17-jdk unzip zlib1g-dev libffi-dev libssl-dev libncurses-dev
    - name: Setup Android SDK
      run: |
        # SDK dizinini oluştur ve içine araçları indir
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        
        # Lisansları kabul et
        export PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin
        yes | sdkmanager --licenses
        
        # Build-tools ve SDK'yı kur
        sdkmanager "build-tools;34.0.0" "platforms;android-34" "platform-tools"
    - name: Install buildozer
      run: pip install buildozer
    - name: Build APK
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        buildozer android debug
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
